### ISSUE TITLE
采用plus账号的refresh token无法正常返回

### ISSUE THREAD

**Issue by 01PAfXWT** [Yanyutin753/refresh-gpt-chat#3]
首先，谢谢大佬的工作。已经给star。
原来一直用你的tokentools+pandoranext使用，自己在用主要是chat2api功能，用来一些应用的chatgpt plugin上。
根据https://apifox.com/apidoc/shared-4b9a7517-3f80-47a1-84fc-fcf78827a04a的文档说明，很快就将ninja和refresh-gpt-chat搭建好。从https://chat.freegpts.org/applelogin获得refresh token。
但是测试过程中发现：
用普通3.5账号，可以正常将refresh token当作api使用。如图：
![image](https://github.com/Yanyutin753/refresh-gpt-chat/assets/62333223/286090bf-0eb8-41bf-adc3-6a6c2977a2d0)
但是用plus的账号，无论是用gpt-3.5-turbo还是gpt-4.0，返回的message的content都是空值。
![image](https://github.com/Yanyutin753/refresh-gpt-chat/assets/62333223/78f3dbc8-4184-48ff-a5ba-5fd778aa85d0)

这个问题要如何解决，这个和直接用access token用ninja的/v1/chat/completions返回的是一样的。

**Comment by Yanyutin753** [comment]
更新ninja吧 撞wss了，用pamdoratov1api转backend使用

**Comment by Yanyutin753** [comment]
ninja的v1/wss没解决，用ninja得backend

**Comment by 01PAfXWT** [comment]
收到。谢谢。
